### ISSUE TITLE
Works wrong with urls without protocol

### ISSUE THREAD

**Issue by super-romeo** [QDenka/Punycode#2]
Thank you for module!

But all my tests failed:

>      ['roman.exe', 'roman.exe'],
>      ['сдай-лом.рф', 'xn----7sblvlgns.xn--p1ai'],
>      ['сдай-лом.рф/пример', 'xn----7sblvlgns.xn--/-jtbiqnecd3a'],
>      ['https://сдай-лом.рф/пример', 'xn----7sblvlgns.xn--/-jtbiqnecd3a'],

**Comment by QDenka** [comment]
@superromeo 
initially, the service was conceived as for punycode for host, but I can modify it for more extensive use

**Comment by QDenka** [comment]
https://github.com/QDenka/Punycode/releases/tag/1.2.0
